version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: iotdb
      MYSQL_USER: iotuser
      MYSQL_PASSWORD: iotpass
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    restart: always

  neo4j:
    image: neo4j:5
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/testpass
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j:/data
    restart: always

  app:
    build: ./app
    container_name: iot-python-app
    depends_on:
      - mosquitto
      - mysql
      - mongodb
      - neo4j
    ports:
      - "5050:5000"
    volumes:
      - ./app:/app
    environment:
      - MQTT_BROKER=mosquitto
      - MYSQL_HOST=mysql
      - MYSQL_USER=iotuser
      - MYSQL_PASSWORD=iotpass
      - MYSQL_DB=iotdb
      - MONGO_HOST=mongodb
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testpass
    command: ["python", "app.py"]
    restart: always
